// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {ERC721} from "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";
import {Base64} from "@openzeppelin/contracts/utils/Base64.sol";
import {Strings} from "@openzeppelin/contracts/utils/Strings.sol";

/**
 * @title Sonoglyph
 * @notice ERC-721 of completed Sonoglyph descents (Hermes Hackathon submission).
 *
 * Each token preserves the full record of one descent:
 *   - `glyph`        — ASCII art (~32x16) generated by Kimi K2
 *   - `journal`      — poetic field journal (~3 paragraphs, <=520 chars)
 *   - `audioCid`     — IPFS CIDv1 of the recorded audio (Pinata-pinned)
 *   - `sessionCode`  — 6-char descent code, ties the token to its server log
 *   - `creator`      — address that completed the descent
 *   - `mintedAt`     — block.timestamp at mint
 *
 * Mint policy: only the contract owner (the bridge's signing wallet) can mint.
 * This trades trustlessness for curation — we know every minted token came
 * from a real completed descent the bridge witnessed end-to-end. The bridge
 * mints to the player's chosen address (passed in `to`).
 *
 * Rendering: `tokenURI(id)` is fully on-chain. Returns
 *   data:application/json;base64,<json>
 * where the JSON contains:
 *   - `name`            — "Sonoglyph #<id>"
 *   - `description`     — the journal (escaped for JSON)
 *   - `image`           — data:image/svg+xml;base64,<svg> with the glyph
 *                         drawn as monospace text on a black canvas
 *   - `animation_url`   — ipfs://<audioCid>, lets marketplaces play the
 *                         recording (OpenSea, Rarible, custom viewers)
 *   - `external_url`    — https://sonoglyph.xyz
 *   - `attributes`      — session code, token id, mint timestamp
 *
 * Why everything on-chain (except the audio): glyph + journal are short
 * enough that block storage is cheap on Monad testnet, and pinning them
 * separately would add an off-chain dependency without lowering the
 * on-chain footprint meaningfully. Audio is too large for storage cost
 * to feel right (~5 MB / descent), and IPFS is the right place for it.
 */
contract Sonoglyph is ERC721, Ownable {
    using Strings for uint256;

    struct Descent {
        string glyph;
        string journal;
        string audioCid;
        string sessionCode;
        address creator;
        uint64 mintedAt;
    }

    /// @notice Per-token descent payload. Read via {descentOf}.
    mapping(uint256 => Descent) private _descents;

    /// @notice Last assigned tokenId; tokens are 1-indexed (first mint is #1).
    uint256 public lastTokenId;

    event DescentMinted(
        uint256 indexed tokenId,
        address indexed to,
        string sessionCode,
        string audioCid
    );

    /**
     * @param initialOwner Address that will be granted Ownable-owner rights.
     *                     This MUST be the bridge's signing wallet — only
     *                     this address can call {mintDescent}.
     */
    constructor(address initialOwner)
        ERC721("Sonoglyph", "SGLYPH")
        Ownable(initialOwner)
    {}

    // -------------------------------------------------------------------------
    // Mint
    // -------------------------------------------------------------------------

    /**
     * @notice Mint a Sonoglyph descent NFT to `to`. Only the contract owner
     *         (the bridge wallet) may call this.
     *
     * @param to           Player's destination address.
     * @param glyph        ASCII art block; UTF-8 bytes are stored verbatim.
     * @param journal      Poetic prose; UTF-8 bytes stored verbatim.
     * @param audioCid     IPFS CIDv1 of the recording (no `ipfs://` prefix).
     * @param sessionCode  6-char descent code from the bridge.
     * @return tokenId     Newly minted tokenId (always lastTokenId after call).
     */
    function mintDescent(
        address to,
        string calldata glyph,
        string calldata journal,
        string calldata audioCid,
        string calldata sessionCode
    ) external onlyOwner returns (uint256 tokenId) {
        require(to != address(0), "to=0");
        require(bytes(glyph).length > 0, "empty glyph");
        require(bytes(audioCid).length > 0, "empty audioCid");

        tokenId = ++lastTokenId; // 1-indexed
        _descents[tokenId] = Descent({
            glyph: glyph,
            journal: journal,
            audioCid: audioCid,
            sessionCode: sessionCode,
            creator: to,
            mintedAt: uint64(block.timestamp)
        });

        // _safeMint reverts if `to` is a contract that doesn't accept ERC-721;
        // for hackathon usage 99% of mints go to EOAs anyway.
        _safeMint(to, tokenId);

        emit DescentMinted(tokenId, to, sessionCode, audioCid);
    }

    // -------------------------------------------------------------------------
    // Reads
    // -------------------------------------------------------------------------

    /// @notice Full descent payload for a given tokenId.
    function descentOf(uint256 tokenId) external view returns (Descent memory) {
        _requireOwned(tokenId);
        return _descents[tokenId];
    }

    /**
     * @notice Token URI — fully on-chain JSON+SVG dataURL.
     * @dev Returns `data:application/json;base64,<...>` where the decoded
     *      JSON has `image` (SVG dataURL) and `animation_url` (ipfs://) fields.
     */
    function tokenURI(uint256 tokenId) public view override returns (string memory) {
        _requireOwned(tokenId);
        Descent memory d = _descents[tokenId];

        string memory svg = _renderSvg(d);
        string memory imageDataUrl = string.concat(
            "data:image/svg+xml;base64,",
            Base64.encode(bytes(svg))
        );

        // Full JSON metadata. We escape user content (glyph, journal) for
        // JSON-string safety; everything else is contract-controlled.
        string memory json = string.concat(
            '{"name":"Sonoglyph #', tokenId.toString(), '"',
            ',"description":"', _escapeJson(d.journal), '"',
            ',"image":"', imageDataUrl, '"',
            ',"animation_url":"ipfs://', d.audioCid, '"',
            ',"external_url":"https://sonoglyph.xyz"',
            ',"attributes":', _renderAttributes(d, tokenId),
            "}"
        );

        return string.concat(
            "data:application/json;base64,",
            Base64.encode(bytes(json))
        );
    }

    // -------------------------------------------------------------------------
    // SVG rendering — pure functions, all deterministic from token data.
    // -------------------------------------------------------------------------

    function _renderSvg(Descent memory d) internal pure returns (string memory) {
        // 800x800 canvas. Glyph rendered via foreignObject so we can use
        // CSS `white-space: pre` and a real monospace stack — the glyph's
        // visual identity depends entirely on grid alignment.
        return string.concat(
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 800" preserveAspectRatio="xMidYMid meet">',
            '<rect width="800" height="800" fill="#050507"/>',
            '<foreignObject x="40" y="80" width="720" height="600">',
            '<div xmlns="http://www.w3.org/1999/xhtml" style="font-family:ui-monospace,Menlo,Consolas,monospace;color:#c9885b;font-size:18px;line-height:1.05;text-align:center;white-space:pre;letter-spacing:0.05em">',
            _escapeHtml(d.glyph),
            '</div></foreignObject>',
            '<text x="400" y="730" font-family="ui-monospace,Menlo,monospace" font-size="14" fill="#6a6660" text-anchor="middle" letter-spacing="3">',
            "SONOGLYPH",
            "</text>",
            '<text x="400" y="755" font-family="ui-monospace,Menlo,monospace" font-size="11" fill="#4a463f" text-anchor="middle" letter-spacing="2">',
            _escapeHtml(d.sessionCode),
            "</text>",
            "</svg>"
        );
    }

    function _renderAttributes(Descent memory d, uint256 tokenId)
        internal
        pure
        returns (string memory)
    {
        return string.concat(
            "[",
            '{"trait_type":"Session","value":"', _escapeJson(d.sessionCode), '"},',
            '{"trait_type":"Token","value":', tokenId.toString(), '},',
            '{"trait_type":"Minted","display_type":"date","value":',
                uint256(d.mintedAt).toString(),
            '},',
            '{"trait_type":"Creator","value":"', Strings.toHexString(d.creator), '"}',
            "]"
        );
    }

    // -------------------------------------------------------------------------
    // String escaping. Byte-level — UTF-8 multi-byte sequences pass through
    // untouched because their continuation bytes are all 0x80-0xBF, none of
    // which are JSON or XML special characters.
    // -------------------------------------------------------------------------

    /// @dev Escape JSON string content. Handles ", \\, control chars (\u00XX).
    function _escapeJson(string memory s) internal pure returns (string memory) {
        bytes memory bs = bytes(s);
        // First pass: count output length.
        uint256 outLen;
        for (uint256 i = 0; i < bs.length; i++) {
            uint8 c = uint8(bs[i]);
            if (c == 0x22 || c == 0x5c) {
                outLen += 2; // \" or \\
            } else if (c == 0x08 || c == 0x09 || c == 0x0a || c == 0x0c || c == 0x0d) {
                outLen += 2; // \b \t \n \f \r
            } else if (c < 0x20) {
                outLen += 6; // \u00XX
            } else {
                outLen += 1;
            }
        }
        bytes memory out = new bytes(outLen);
        uint256 j = 0;
        for (uint256 i = 0; i < bs.length; i++) {
            uint8 c = uint8(bs[i]);
            if (c == 0x22) {
                out[j++] = "\\";
                out[j++] = '"';
            } else if (c == 0x5c) {
                out[j++] = "\\";
                out[j++] = "\\";
            } else if (c == 0x08) {
                out[j++] = "\\";
                out[j++] = "b";
            } else if (c == 0x09) {
                out[j++] = "\\";
                out[j++] = "t";
            } else if (c == 0x0a) {
                out[j++] = "\\";
                out[j++] = "n";
            } else if (c == 0x0c) {
                out[j++] = "\\";
                out[j++] = "f";
            } else if (c == 0x0d) {
                out[j++] = "\\";
                out[j++] = "r";
            } else if (c < 0x20) {
                out[j++] = "\\";
                out[j++] = "u";
                out[j++] = "0";
                out[j++] = "0";
                out[j++] = _hexNibble(c >> 4);
                out[j++] = _hexNibble(c & 0x0f);
            } else {
                out[j++] = bs[i];
            }
        }
        return string(out);
    }

    /// @dev Escape XML/HTML text node content. `<`, `>`, `&`, `"`, `'`.
    function _escapeHtml(string memory s) internal pure returns (string memory) {
        bytes memory bs = bytes(s);
        uint256 outLen;
        for (uint256 i = 0; i < bs.length; i++) {
            uint8 c = uint8(bs[i]);
            if (c == 0x3c) outLen += 4; // &lt;
            else if (c == 0x3e) outLen += 4; // &gt;
            else if (c == 0x26) outLen += 5; // &amp;
            else if (c == 0x22) outLen += 6; // &quot;
            else if (c == 0x27) outLen += 6; // &apos;
            else outLen += 1;
        }
        bytes memory out = new bytes(outLen);
        uint256 j = 0;
        for (uint256 i = 0; i < bs.length; i++) {
            uint8 c = uint8(bs[i]);
            if (c == 0x3c) {
                out[j++] = "&"; out[j++] = "l"; out[j++] = "t"; out[j++] = ";";
            } else if (c == 0x3e) {
                out[j++] = "&"; out[j++] = "g"; out[j++] = "t"; out[j++] = ";";
            } else if (c == 0x26) {
                out[j++] = "&"; out[j++] = "a"; out[j++] = "m"; out[j++] = "p"; out[j++] = ";";
            } else if (c == 0x22) {
                out[j++] = "&"; out[j++] = "q"; out[j++] = "u"; out[j++] = "o";
                out[j++] = "t"; out[j++] = ";";
            } else if (c == 0x27) {
                out[j++] = "&"; out[j++] = "a"; out[j++] = "p"; out[j++] = "o";
                out[j++] = "s"; out[j++] = ";";
            } else {
                out[j++] = bs[i];
            }
        }
        return string(out);
    }

    function _hexNibble(uint8 nibble) internal pure returns (bytes1) {
        return nibble < 10
            ? bytes1(uint8(0x30) + nibble) // '0'..'9'
            : bytes1(uint8(0x57) + nibble); // 'a'..'f'
    }
}
